### ISSUE TITLE
能不能加个开关QAQ

### ISSUE THREAD

**Issue by Levantie-cyl** [lgc-NB2Dev/nonebot-plugin-fuckyou#1]
比如开启暴力模式然后使用词库

**Comment by lgc2333** [comment]
说详细点

**Comment by Cyllevantie** [comment]
> 比如开启xx模式，然后启用这个库的json，关闭就停用这个库的json
不然还得去配置文件里每次启动重启调开关，感觉有点麻烦QAQ

**Comment by lgc2333** [comment]
不难做，但是感觉不太好，希望能给点好的解决方案，麻烦点也无所谓
