### ISSUE TITLE
大佬可不可以搞一个群黑名单

### ISSUE THREAD

**Issue by VAHua** [lgc-NB2Dev/nonebot-plugin-fuckyou#3]
呜呜呜，今天在工作群里，同事发了句sql，里面应该包含了SB两个字，触发了骂人，我被说了，大佬可以整个群黑名单吗

**Comment by lgc2333** [comment]
可以暂时使用 nonebot-plugin-manager 插件，或者看看这个 https://github.com/Dogend233/nonebot-plugin-fuckyou-reset
暂时不考虑在本插件里做

**Comment by VAHua** [comment]
好的，谢谢大佬

**Comment by lgc2333** [comment]
https://github.com/lgc-NB2Dev/nonebot-plugin-fuckyou/commit/fbd8af2976558e133090add1ae39ac117c8d0a41

**Comment by XieXiLin2** [comment]
已发版，更新插件至 v0.3.0 即可。

**Comment by VAHua** [comment]
谢谢大佬，爱你，给你点小星星
