### ISSUE TITLE
FUCKYOU_GROUP_BLACKLIST参数不知道如何填写，列表、元组、集合都报错，希望大佬指导一下

### ISSUE THREAD

**Issue by VAHua** [lgc-NB2Dev/nonebot-plugin-fuckyou#5]

**Comment by lgc2333** [comment]
字符串列表

**Comment by VAHua** [comment]
> 字符串列表

经测试，似乎不行
![image](https://github.com/lgc-NB2Dev/nonebot-plugin-fuckyou/assets/129832780/5f0377a0-cf31-478e-9083-c262cfe35065)
![image](https://github.com/lgc-NB2Dev/nonebot-plugin-fuckyou/assets/129832780/df6a8d1b-2756-46ea-a508-7cdff6055fac)

**Comment by lgc2333** [comment]
双引号，nb是按json格式解析env的

**Comment by VAHua** [comment]
收到，已搞定
